### ISSUE TITLE
Send inquiry Endpoint

### ISSUE THREAD

**Issue by romyngo** [poltak/brightsparqe-web#13]
/api/contact: to send email to Brightsparqe through the webform

**Comment by poltak** [comment]
Have we got a designated email address from Charbel to send inquiries to?

**Comment by poltak** [comment]
Mostly done: 86de69ebd7c2d77ce9fe5499c8ff65731f46ed09

**Comment by poltak** [comment]
d02a9cae1a914c02e000cc5dd19f033181fd18b2
