### ISSUE TITLE
Add email auth to send outgoing mail from backend

### ISSUE THREAD

**Issue by romyngo** [poltak/brightsparqe-web#23]
Authentication using do_not_reply@brightsparqe.org

**Comment by poltak** [comment]
Added in queries@brightsparqe.org address to handle form enquiries:
aacfa09646eab43f1004742ec9995a5312f80f15

Still need more information on how you will use do_not_reply.

**Comment by poltak** [comment]
Subscribe to newsletter endpoint is now using do_not_reply@brightsparqe.org email, as per #12

**Comment by poltak** [comment]
fixed up and working on deployment
