### ISSUE TITLE
Add a statement field to petition table and API

### ISSUE THREAD

**Issue by romyngo** [poltak/brightsparqe-web#32]
Example

Name: Letter to Australian Supermarkets

Statement: Australian supermarkets to donate all their unsold and
edible food to charities to feed our homeless and disadvantaged.

Description: Australia is renowned as the luckiest country in the world however there are over 120,000 homeless men women and children.  Homelessness is not a choice it may comes from a number of different factors including domestic and family violence, financial difficulties, housing stress, relationship or family breakdowns, housing affordability stress, physical abuse, drug and alcohol abuse and mental illness. 
The Australian Bureau of Statistics have revealed that over 105,000 people were formally declared as homeless in 2011 up from over 89,000 in 2006.  The Global Financial Crisis and the closure of many of Australia’s manufacturing has increased the likelihood more people may become homeless.I would like our supermarkets to commit to not throwing edible food each day/week.  Food being placed in bins does not benefit our society and I am a firm believer it should be given to charities to distribute to the homeless/needy rather than being placed in a bin and into a landfill.

**Comment by poltak** [comment]
Done: b9a9fe461362722c88027b36935edd88321c9873
