### ISSUE TITLE
Get clarification from Charbel to resolve issues listed in the issue tracker

### ISSUE THREAD

**Issue by romyngo** [poltak/brightsparqe-web#33]
Issue 3: What photo? Where to show them? Must provide screenshot
Issue 4: Clarify "Still isn't right" by drawing out where to place each bullet point. Must provide screenshot
Issue 6: Send original image (map of Australia)
Issue 11: Send original images (social icons)
Issue 15: Send missing photos of Charbel and Sana

**Comment by poltak** [comment]
Issue 19: I would like the record when saved date and time stamped when I view the database online and when I extract the data.  I do not require the user to view the date and time stamp on the screen when they are populating and submitting the petition, thank you.

Issue 3: I will provide you an example shortly.
Issue 4: I will provide you an example shortly.
Issue 6: I shall send it through shortly.
Issue 11: Leave the icons as they are
Issue 15: Will be scheduling a photo shot hopefully this week if not next.
