### ISSUE TITLE
Remove unused field when signing petition

### ISSUE THREAD

**Issue by romyngo** [poltak/brightsparqe-web#36]
Should have the following only listed below; only.
1. TItle
2. First Name
3. Last Name
4. Email
5. City
6. State
7. Country
8. I am signing this because 

Backend: removed unused fields from required params in API end point
Frontend: remove

**Comment by poltak** [comment]
Backend done: 78d5d6fd350e168c888e0a0bf27209245f44c32b

For the address city, state, and countries, send the "postal_" prefixed params in your XHR from frontend (as opposed to the "billing_" prefixed params).
