### ISSUE TITLE
Display petition counter 

### ISSUE THREAD

**Issue by romyngo** [poltak/brightsparqe-web#37]
I would like the count of online peitions everytime a person clicks the button to sign-up it shows the number identical to the donations

Backend: create endpoint
Frontend: display

**Comment by poltak** [comment]
Backend logic in place and tested: 3675aee63638504fcc6e030f2441c4b70e4c3b74

**Comment by romyngo** [comment]
Need to return target (targeted number of signees for a petition )as well.
- Add a field *target* to petition table
- Return it together with this API

**Comment by poltak** [comment]
Fixed by adding 'target' column to petitions table.

No code changes necessary.
